### ISSUE TITLE
Considered using goreleaser for build / release process?

### ISSUE THREAD

**Issue by wolfeidau** [spezam/eventbridge-cli#6]
Project site is at https://github.com/goreleaser/goreleaser and I think they have a github action to help out.

I use a bunch of projects like https://github.com/golangci/golangci-lint which use it.

Great utility BTW 👍

**Comment by spezam** [comment]
Thanks @wolfeidau I'll check it out, seems a very powerful and mature project!

**Comment by spezam** [comment]
Goreleaser implemented with v1.0.1.
Reccomended project!
